PMS/Models/ErrorViewModel.cs
using System;

namespace PMS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PMS/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PMS.Models
{
    public class Project
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public double Budget { get; set; }
    }
}

PMS/Models/Task.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PMS.Models
{
    public class Task
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }


        public Project Project { get; set; }
        public int ProjectID { get; set; }
    }
}

PMS/ViewModels/AddProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PMS.ViewModels
{
    public class AddProjectViewModel
    {
        [Required]
        [Display(Name = "Project Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "You must give your project a description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Budget")]
        public int Budget { get; set; }


        [Required]
        [Display(Name = "StartDate")]
        [DataType(DataType.Date)]
        public int StartDate { get; set; }
        

        [Required]
        [Display(Name = "EndDate")]
        public int EndDate { get; set; }

        public int ID { get; set; }


        public AddProjectViewModel()
        {
        }
    }
}

PMS/ViewModels/AddTaskViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PMS.ViewModels
{
    public class AddTaskViewModel
    {
        
        

            [Required]
            [Display(Name = "Task Name")]
            public string Name { get; set; }

            [Required(ErrorMessage = "You must give your task a description")]
            public string Description { get; set; }

            [Required]
            [Display(Name = "project")]
            public int ProjectID { get; set; }

            public int ID { get; set; }


            public AddTaskViewModel()
            {
            }
        
    }
}

PMS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PMS.Models;

namespace PMS.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PMS/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PMS.Data;
using PMS.Models;
using PMS.ViewModels;

namespace PMS.Controllers
{
    public class ProjectController : Controller
    {
        private PMSDbContext context;

        public ProjectController(PMSDbContext dbContext)
        {
            context = dbContext;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Project> projects = context.Projects.ToList();

            return View(projects);
        }

        [HttpGet]
        public IActionResult Add()
        {
            AddProjectViewModel addProjectViewModel = new AddProjectViewModel();
            return View(addProjectViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddProjectViewModel addProjectViewModel)
        {
            if (ModelState.IsValid)
            {
                // Add the new project to my existing projects
                Project newProject = new Project
                {
                    Name = addProjectViewModel.Name,
                    Description = addProjectViewModel.Description,
                    Budget = addProjectViewModel.Budget,
                    //StartDate = addProjectViewModel.StartDate,
                    //EndDate = addProjectViewModel.EndDate


                };

                context.Projects.Add(newProject);
                context.SaveChanges();

                return Redirect("/Project");
            };

            return View(addProjectViewModel);
        }

        public IActionResult Delete()
        {
            ViewBag.title = "Delete Projects";
            ViewBag.projects = context.Projects.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] projectIds)
        {
            foreach (int projectId in projectIds)
            {
                Project theProject = context.Projects.Single(c => c.ID == projectId);
                context.Projects.Remove(theProject);
            }

            context.SaveChanges();

            return Redirect("/Project");
        }
    }
}

PMS/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Mvc;
using PMS.Data;
using Microsoft.EntityFrameworkCore;
using PMS.Models;
using PMS.ViewModels;

namespace PMS.Controllers
{
    public class TaskController : Controller
    {
        private readonly PMSDbContext context;

        public TaskController(PMSDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            IList<Task> tasks = context.Tasks.ToList();

            //IList<Task> tasks = context.Tasks.Include(c => c.Project).ToList();
            return View(tasks);
        }

        [HttpGet]
        public IActionResult Add()
        {
            AddTaskViewModel addTaskViewModel = new AddTaskViewModel();
            return View(addTaskViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddTaskViewModel addTaskViewModel)
        {
            if (ModelState.IsValid)
            {
                // Add the new task to my existing tasks
                Task newTask = new Task
                {
                    Name = addTaskViewModel.Name,
                    Description = addTaskViewModel.Description,
                    ProjectID = addTaskViewModel.ProjectID
                };

                context.Tasks.Add(newTask);
                context.SaveChanges();

                return Redirect("/Task");
            };

            return View(addTaskViewModel);
        }

        public IActionResult Delete()
        {
            ViewBag.title = "Delete Tasks";
            ViewBag.Tasks = context.Tasks.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] taskIds)
        {
            foreach (int taskId in taskIds)
            {
                Task theTask = context.Tasks.Single(c => c.ID == taskId);
                context.Tasks.Remove(theTask);
            }

            context.SaveChanges();

            return Redirect("/Task");
        }
    }
}

PMS/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

PMS/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PMS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

PMS/Views/Project/Add.cshtml
@model PMS.ViewModels.AddProjectViewModel


<h2>Add Project</h2>


<form asp-controller="Project" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>

    <div class="form-group">
        <label asp-for="StartDate"></label>
        <input type="DateTime" class="datefield" asp-for="StartDate" />
        
    </div>

    <div class="form-group">
        <label asp-for="EndDate"></label>
        <input type="DateTime" class="datefield" asp-for="EndDate" />
        
    </div>

    <div class="form-group">
        <label asp-for="Budget"></label>
        <input class="form-control" asp-for="Budget" />
        <span asp-validation-for="Budget"></span>
    </div>

    <input type="submit" value="Add Project" />


</form>

PMS/Views/Project/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}


<h1>@ViewBag.title</h1>

<form method="post">

    @foreach (var project in ViewBag.projects)
    {
        <input type="checkbox" name="projectIds" id="@project.ID" value="@project.ID" />
        <label for="@project.ID">@project.Name</label>
        <br />
    }

    <input type="submit" value="Remove Selected Project(s)" />
</form>

PMS/Views/Project/Index.cshtml
@model List<PMS.Models.Project>
<h1>@ViewBag.Title</h1>


<table class="table">

    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Budget</th>
    </tr>

    @foreach (var project in Model)
    {
        <tr>
            <td>@project.Name</td>
            <td>@project.Description</td>
            <td>@project.StartDate</td>
            <td>@project.EndDate</td>
            <td>@project.Budget</td>
          
            
        </tr>
    }
</table>

@if (Model.Count == 0)
{
    <p>No projects yet!</p>
}

<p><a asp-controller="Project" asp-action="Add">Add Project</a></p>
<a asp-controller="Project" asp-action="Delete">Delete Project</a>

PMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PMS</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">PMS</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-controller="Project" asp-action="Index">Projects</a></li>
                    <li><a asp-controller="Task" asp-action="Index">Tasks</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - PMS</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

PMS/Views/Task/Add.cshtml
@model PMS.ViewModels.AddTaskViewModel
@{
    ViewData["Title"] = "Add";
}

<h2>Add Task</h2>

<form asp-controller="Task" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>

    @*<div class="form-group">
        <label asp-for="ProjectID"></label>
        <input class="form-control" asp-for="ProjectID" />
        <span asp-validation-for="ProjectID"></span>
    </div>*@

    <input type="submit" value="Add Task" />


</form>

PMS/Views/Task/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

PMS/Views/Task/Index.cshtml
@model List<PMS.Models.Task>
<h1>@ViewBag.Title</h1>




<table class="table">

    <tr>
       <th>Name</th>
       <th>Description</th>
       <th>ProjectID</th>
    </tr>

    @foreach (var task in Model)
    {
        <tr>
            <td>@task.Name</td>
            <td>@task.Description</td>
            <td>@task.ProjectID</td>
        </tr>
    }

   
</table>

@if (Model.Count == 0)
{
    <p>No task yet!</p>
}

<p><a asp-controller="Task" asp-action="Add">Add Task</a></p>
<p><a asp-controller="Task" asp-action="Delete">Delete Task</a></p>